name: 'Enable Red Hat entitled podman builds'
inputs:
  org:
    description: 'Red Hat account organization'
  activationkey:
    description: 'Red Hat account activation key'
  image:
    description: 'Container image to use to run subscription-manager register'
    default: 'registry.access.redhat.com/ubi10'
runs:
  using: 'composite'
  steps:
    - run: mkdir -p /tmp/{etc-pki-entitlement,rhsm}-"${RUN_ID}"
      env:
        RUN_ID: ${{ github.run_id }}
      shell: bash
    - run: |
        NAME=$( echo "$RUN_URL" | sed 's#^https://##;s#/#-#g' )
        podman run --rm --name="$NAME" \
          -v "/tmp/etc-pki-entitlement-${RUN_ID}":/etc/pki/entitlement-out:z \
          -v "/tmp/rhsm-${RUN_ID}":/etc/rhsm-out:z \
          -e SM_ORG="$INPUTS_ORG" \
          -e SM_KEY="$INPUTS_ACTIVATIONKEY" \
          -e SYSTEM_NAME="$NAME" \
          "$INPUTS_IMAGE" \
          bash -c '/usr/sbin/subscription-manager register \
                     --org="$SM_ORG" \
                     --activationkey="$SM_KEY" \
                     --name="$SYSTEM_NAME" \
                   && cp /etc/pki/entitlement/* /etc/pki/entitlement-out/ \
                   && cp -r /etc/rhsm/ca /etc/rhsm/rhsm.conf /etc/rhsm-out \
                   && /usr/sbin/subscription-manager unregister'
      env:
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        RUN_ID: ${{ github.run_id }}
        INPUTS_IMAGE: ${{ inputs.image }}
        INPUTS_ORG: ${{ inputs.org }}
        INPUTS_ACTIVATIONKEY: ${{ inputs.activationkey }}
      shell: bash
    - run: for i in etc-pki-entitlement rhsm ; do echo "/tmp/$i-${RUN_ID}:/run/secrets/$i" ; done | sudo tee -a /etc/containers/mounts.conf
      env:
        RUN_ID: ${{ github.run_id }}
      shell: bash
